import { useState, useEffect, useCallback, useRef } from 'react'
import { X, BookOpen, Sparkles, Image as ImageIcon } from 'lucide-react'
import { Book, booksAPI } from '../api/books'
import { bookshelfAPI, BookshelfItem, BookshelfStatus } from '../api/bookshelf'
import { showToast } from './ToastContainer'
import ConfirmDialog from './ConfirmDialog'

interface BookDetailModalProps {
  book: Book | null
  isOpen: boolean
  onClose: () => void
  onAskAgent: (bookId: number, bookTitle?: string) => void
}

// 第三方平台搜索/购买页
const WEREAD_SEARCH_URL = 'https://weread.qq.com/web/search/books?author={author}&title={title}'
const JD_SEARCH_URL = 'https://search.jd.com/Search?keyword={keyword}'
const DANGDANG_SEARCH_URL = 'https://search.dangdang.com/?key={title}'

export default function BookDetailModal({
  book,
  isOpen,
  onClose,
  onAskAgent,
}: BookDetailModalProps) {
  const [isAdding, setIsAdding] = useState(false)
  const [displayBook, setDisplayBook] = useState<Book | null>(book)
  const [isGeneratingDesc, setIsGeneratingDesc] = useState(false)
  const [isGeneratingCover, setIsGeneratingCover] = useState(false)
  const [, setIsAiGeneratedDesc] = useState(false)
  const [isAiGeneratedCover, setIsAiGeneratedCover] = useState(false)
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false)
  const [bookshelfStatus, setBookshelfStatus] = useState<BookshelfStatus | null>(null)
  const [bookshelfId, setBookshelfId] = useState<number | null>(null)
  const [isLoadingBookshelf, setIsLoadingBookshelf] = useState(false)
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
  const closeButtonRef = useRef<HTMLButtonElement>(null)
  /** 简介逐字展示：全文与已展示长度 */
  const [descStreamingFull, setDescStreamingFull] = useState('')
  const [descStreamingLen, setDescStreamingLen] = useState(0)
  const descStreamingTimerRef = useRef<ReturnType<typeof setInterval> | null>(null)

  // 简介逐字展示（与 AI 书童同节奏）
  useEffect(() => {
    const text = displayBook?.description?.trim()
    if (!text || text === '暂无简介') {
      setDescStreamingFull('')
      setDescStreamingLen(0)
      if (descStreamingTimerRef.current) {
        clearInterval(descStreamingTimerRef.current)
        descStreamingTimerRef.current = null
      }
      return
    }
    setDescStreamingFull(text)
    setDescStreamingLen(0)
  }, [displayBook?.description])

  useEffect(() => {
    if (!descStreamingFull) return
    const total = descStreamingFull.length
    const step = 2
    descStreamingTimerRef.current = setInterval(() => {
      setDescStreamingLen((prev) => {
        const next = Math.min(prev + step, total)
        if (next >= total && descStreamingTimerRef.current) {
          clearInterval(descStreamingTimerRef.current)
          descStreamingTimerRef.current = null
        }
        return next
      })
    }, 40)
    return () => {
      if (descStreamingTimerRef.current) {
        clearInterval(descStreamingTimerRef.current)
        descStreamingTimerRef.current = null
      }
    }
  }, [descStreamingFull])

  // 弹窗打开时设置页面标题，关闭时恢复；Esc 关闭；焦点移入
  useEffect(() => {
    if (!isOpen) return
    const prevTitle = document.title
    if (displayBook?.title) document.title = `阅心 - ${displayBook.title}`
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', onKeyDown)
    const t = setTimeout(() => closeButtonRef.current?.focus(), 100)
    return () => {
      document.title = prevTitle
      window.removeEventListener('keydown', onKeyDown)
      clearTimeout(t)
    }
  }, [isOpen, displayBook?.title, onClose])

  // 自动生成简介（如果没有简介）
  const handleAutoGenerateDescription = useCallback(async (bookId: number) => {
    if (isGeneratingDesc) return // 防止重复调用
    setIsGeneratingDesc(true)
    try {
      const res = await booksAPI.generateDescription(bookId)
      setDisplayBook((prev) => prev ? { ...prev, description: res.description } : null)
      setIsAiGeneratedDesc(true)
    } catch (error: any) {
      console.error('自动生成简介失败:', error)
      // 静默失败，不显示 toast
    } finally {
      setIsGeneratingDesc(false)
    }
  }, [isGeneratingDesc])

  // 自动生成封面（如果没有封面）
  const handleAutoGenerateCover = useCallback(async (bookId: number) => {
    if (isGeneratingCover) return // 防止重复调用
    setIsGeneratingCover(true)
    try {
      const res = await booksAPI.generateCover(bookId)
      setDisplayBook((prev) => prev ? { ...prev, cover_url: res.cover_url } : null)
      setIsAiGeneratedCover(true)
    } catch (error: any) {
      console.error('自动生成封面失败:', error)
      // 静默失败，不显示 toast
    } finally {
      setIsGeneratingCover(false)
    }
  }, [isGeneratingCover])

  // 检查书籍是否在书架中
  const checkBookshelfStatus = useCallback(async (bookId: number) => {
    setIsLoadingBookshelf(true)
    try {
      const allItems = await bookshelfAPI.getBookshelf()
      const item = allItems.find((item: BookshelfItem) => item.book.id === bookId)
      if (item) {
        setBookshelfStatus(item.status as BookshelfStatus)
        setBookshelfId(item.id)
      } else {
        setBookshelfStatus(null)
        setBookshelfId(null)
      }
    } catch (error: any) {
      console.error('检查书架状态失败:', error)
      setBookshelfStatus(null)
      setBookshelfId(null)
    } finally {
      setIsLoadingBookshelf(false)
    }
  }, [])

  // 当 modal 打开且 book 变化时，自动生成缺失的简介和封面，并检查书架状态
  useEffect(() => {
    if (book && isOpen && !hasAutoGenerated) {
      setDisplayBook(book)
      setHasAutoGenerated(true)
      const descText = book.description?.trim()
      if (descText && descText !== '暂无简介') {
        setDescStreamingFull(descText)
        setDescStreamingLen(0)
      } else {
        setDescStreamingFull('')
        setDescStreamingLen(0)
      }
      // 检查书架状态
      checkBookshelfStatus(book.id)
      
      // 自动生成简介（如果没有简介）
      const needsDescription = !book.description || book.description.trim() === '' || book.description === '暂无简介'
      if (needsDescription) {
        handleAutoGenerateDescription(book.id)
      }
      
      // 自动生成封面（如果没有封面）
      const needsCover = !book.cover_url || book.cover_url.trim() === ''
      if (needsCover) {
        handleAutoGenerateCover(book.id)
      }
    }
    
    // 当 modal 关闭时重置状态
    if (!isOpen) {
      setHasAutoGenerated(false)
      setIsAiGeneratedDesc(false)
      setIsAiGeneratedCover(false)
      setBookshelfStatus(null)
      setBookshelfId(null)
      setDescStreamingFull('')
      setDescStreamingLen(0)
      if (descStreamingTimerRef.current) {
        clearInterval(descStreamingTimerRef.current)
        descStreamingTimerRef.current = null
      }
    }
  }, [book, isOpen, hasAutoGenerated, handleAutoGenerateDescription, handleAutoGenerateCover, checkBookshelfStatus])

  if (!isOpen || !book || !displayBook) return null

  const openExternalSearch = (url: string) => {
    if (!displayBook) return
    window.open(url, '_blank')
  }

  const getWereadUrl = () =>
    WEREAD_SEARCH_URL
      .replace('{title}', encodeURIComponent(displayBook!.title))
      .replace('{author}', encodeURIComponent(displayBook!.author || ''))
  const getJdUrl = () =>
    JD_SEARCH_URL.replace('{keyword}', encodeURIComponent(displayBook!.title))
  const getDangdangUrl = () =>
    DANGDANG_SEARCH_URL.replace('{title}', encodeURIComponent(displayBook!.title))

  const handleAddToBookshelf = async (status: 'to_read' | 'reading' | 'read') => {
    if (!displayBook) return
    
    // 如果书籍已经在书架中且状态相同，则删除
    if (bookshelfStatus === status && bookshelfId) {
      setShowDeleteConfirm(true)
      return
    }
    
    setIsAdding(true)
    try {
      const result = await bookshelfAPI.addToBookshelf({ book_id: displayBook.id, status })
      setBookshelfStatus(status)
      setBookshelfId(result.id)
      const statusText = { to_read: '想读', reading: '在读', read: '已读' }[status]
      showToast(`已添加到书架（${statusText}）`, 'success')
    } catch (error: any) {
      console.error('添加到书架失败:', error)
      showToast('添加失败，请稍后重试', 'error')
    } finally {
      setIsAdding(false)
    }
  }

  const handleDeleteFromBookshelf = async () => {
    if (!bookshelfId) return
    
    setIsAdding(true)
    try {
      await bookshelfAPI.removeFromBookshelf(bookshelfId)
      setBookshelfStatus(null)
      setBookshelfId(null)
      showToast('已从书架移除', 'success')
      setShowDeleteConfirm(false)
    } catch (error: any) {
      console.error('从书架移除失败:', error)
      showToast('移除失败，请稍后重试', 'error')
    } finally {
      setIsAdding(false)
    }
  }

  const handleBackdropClick = (e: React.MouseEvent<HTMLDivElement>) => {
    // 如果点击的是背景蒙层（不是内容区域），则关闭
    if (e.target === e.currentTarget) {
      onClose()
    }
  }

  return (
    <>
      {/* 蒙层背景 - 在导航栏下方 */}
      <div 
        className="fixed inset-0 z-[90] bg-black/50 backdrop-blur-sm"
        onClick={handleBackdropClick}
        style={{ top: 0, left: 0, right: 0, bottom: 0 }}
      />
      {/* 弹窗内容 - 在导航栏上方 */}
      <div 
        className="fixed inset-0 z-[130] flex items-center justify-center p-4 pointer-events-none"
        style={{ top: 0, left: 0, right: 0, bottom: 0 }}
      >
        <div 
          className="bg-card border border-border rounded-xl max-w-2xl w-full max-h-[95vh] overflow-y-auto pointer-events-auto"
          onClick={(e) => e.stopPropagation()}
        >
          {/* 头部 */}
          <div className="sticky top-0 z-10 bg-card border-b border-border px-6 py-4 flex items-center justify-between">
            <h2 className="text-xl font-semibold text-foreground">书籍详情</h2>
            <button
              ref={closeButtonRef}
              onClick={onClose}
              className="p-2 rounded-full hover:bg-background transition-colors"
              aria-label="关闭"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* 内容 */}
          <div className="p-6 space-y-6">
            {/* 封面 + 基本信息 + 添加到书架（同一行） */}
            <div className="flex flex-col md:flex-row gap-6">
            <div className="w-full md:w-48 h-64 flex-shrink-0 relative">
              {displayBook.cover_url ? (
                <>
                  <img
                    src={displayBook.cover_url}
                    alt={displayBook.title}
                    className="w-full h-full object-cover rounded-lg bg-background"
                    loading="lazy"
                    decoding="async"
                  />
                  {isAiGeneratedCover && (
                    <div className="absolute bottom-0 left-0 right-0 bg-black/60 text-white text-xs py-1 px-2 rounded-b-lg text-center">
                      暂无封面
                    </div>
                  )}
                  {isGeneratingCover && (
                    <div className="absolute inset-0 bg-black/40 rounded-lg flex items-center justify-center">
                      <div className="text-white text-sm">生成中...</div>
                    </div>
                  )}
                </>
              ) : (
                <div className="w-full h-full rounded-lg bg-background border border-border flex items-center justify-center">
                  {isGeneratingCover ? (
                    <div className="text-center p-4">
                      <Sparkles className="w-8 h-8 mx-auto mb-2 text-foreground/50 animate-pulse" />
                      <p className="text-sm text-foreground/50">AI 正在生成封面...</p>
                    </div>
                  ) : (
                    <div className="text-center p-4">
                      <ImageIcon className="w-12 h-12 mx-auto mb-2 text-foreground/30" />
                      <p className="text-sm text-foreground/50">暂无封面</p>
                    </div>
                  )}
                </div>
              )}
            </div>
            <div className="flex-1 flex flex-col gap-3 min-h-64 min-w-0">
              <h3 className="text-xl font-bold text-foreground line-clamp-3 break-words" title={displayBook.title}>
                {displayBook.title}
              </h3>
              <p className="text-foreground/70 text-sm">
                作者：{displayBook.author || '未知'}
                {displayBook.isbn && (
                  <><span className="text-foreground/40 mx-1.5">｜</span>ISBN：{displayBook.isbn}</>
                )}
              </p>
              {displayBook.publisher && (
                <p className="text-foreground/70 text-sm">出版社：{displayBook.publisher}</p>
              )}
              {displayBook.rating && (
                <p className="text-foreground/70 text-sm">评分：{displayBook.rating.toFixed(1)}（豆瓣）</p>
              )}
              {/* 加入心灵驿站 - 放在封面右侧 */}
              <div className="mt-auto pt-4">
                <h4 className="text-sm font-medium text-foreground mb-2">加入心灵驿站</h4>
                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={() => handleAddToBookshelf('to_read')}
                    disabled={isAdding || isLoadingBookshelf}
                    className={`px-4 py-2 text-sm border rounded-lg transition-colors disabled:opacity-50 ${
                      bookshelfStatus === 'to_read'
                        ? 'bg-purple-500 text-white border-purple-500 hover:bg-purple-600'
                        : 'border-border hover:bg-background'
                    }`}
                  >
                    想读
                  </button>
                  <button
                    onClick={() => handleAddToBookshelf('reading')}
                    disabled={isAdding || isLoadingBookshelf}
                    className={`px-4 py-2 text-sm border rounded-lg transition-colors disabled:opacity-50 ${
                      bookshelfStatus === 'reading'
                        ? 'bg-purple-500 text-white border-purple-500 hover:bg-purple-600'
                        : 'border-border hover:bg-background'
                    }`}
                  >
                    在读
                  </button>
                  <button
                    onClick={() => handleAddToBookshelf('read')}
                    disabled={isAdding || isLoadingBookshelf}
                    className={`px-4 py-2 text-sm border rounded-lg transition-colors disabled:opacity-50 ${
                      bookshelfStatus === 'read'
                        ? 'bg-purple-500 text-white border-purple-500 hover:bg-purple-600'
                        : 'border-border hover:bg-background'
                    }`}
                  >
                    已读
                  </button>
                </div>
                {/* 获取书籍 - 第三方链接 */}
                <h4 className="text-sm font-medium text-foreground mb-2 mt-4">获取书籍</h4>
                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={() => openExternalSearch(getWereadUrl())}
                    className="px-3 py-2 border border-border rounded-lg hover:bg-background transition-colors text-sm"
                  >
                    微信读书
                  </button>
                  <button
                    onClick={() => openExternalSearch(getJdUrl())}
                    className="px-3 py-2 border border-border rounded-lg hover:bg-background transition-colors text-sm"
                  >
                    京东
                  </button>
                  <button
                    onClick={() => openExternalSearch(getDangdangUrl())}
                    className="px-3 py-2 border border-border rounded-lg hover:bg-background transition-colors text-sm"
                  >
                    当当
                  </button>
                </div>
              </div>
            </div>
            </div>

            {/* 简介 - 独立区域，避免与上方功能重叠 */}
            <div className="relative border-t border-border pt-4 mt-2">
              <h4 className="text-lg font-semibold text-foreground mb-2">简介</h4>
            {displayBook.description && displayBook.description !== '暂无简介' ? (
              <div className="relative min-h-[40px] max-h-48 overflow-y-auto">
                {isGeneratingDesc && (
                  <div className="absolute inset-0 bg-background/90 backdrop-blur-sm flex items-center justify-center rounded z-[1]">
                    <div className="flex flex-col items-center gap-2 text-foreground/70">
                      <div className="relative">
                        <Sparkles className="w-6 h-6 animate-pulse text-purple-500" />
                        <div className="absolute inset-0 animate-ping">
                          <Sparkles className="w-6 h-6 text-purple-500/50" />
                        </div>
                      </div>
                      <span className="text-xs font-medium">AI 正在生成简介...</span>
                      <div className="flex gap-1">
                        <div className="w-1.5 h-1.5 bg-purple-500 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                        <div className="w-1.5 h-1.5 bg-purple-500 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                        <div className="w-1.5 h-1.5 bg-purple-500 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
                      </div>
                    </div>
                  </div>
                )}
                <p className="text-foreground/80 leading-relaxed whitespace-pre-wrap relative z-0">
                  {descStreamingFull ? (
                    <>
                      {descStreamingFull.slice(0, descStreamingLen)}
                      {descStreamingLen < descStreamingFull.length && (
                        <span className="inline-block w-0.5 h-4 ml-0.5 bg-foreground/60 animate-pulse align-middle" aria-hidden />
                      )}
                    </>
                  ) : (
                    displayBook.description
                  )}
                </p>
              </div>
            ) : (
              <div className="min-h-[40px]">
                {isGeneratingDesc ? (
                  <div className="flex flex-col items-center gap-2 py-4 text-foreground/60">
                    <div className="relative">
                      <Sparkles className="w-6 h-6 animate-pulse text-purple-500" />
                      <div className="absolute inset-0 animate-ping">
                        <Sparkles className="w-6 h-6 text-purple-500/50" />
                      </div>
                    </div>
                    <span className="italic text-sm font-medium">AI 正在生成简介...</span>
                    <div className="flex gap-1">
                      <div className="w-1.5 h-1.5 bg-purple-500 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                      <div className="w-1.5 h-1.5 bg-purple-500 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                      <div className="w-1.5 h-1.5 bg-purple-500 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
                    </div>
                  </div>
                ) : (
                  <p className="text-foreground/60 italic">暂无简介</p>
                )}
              </div>
            )}
            </div>

            {/* 聊聊这本书 */}
            <div className="pt-4 border-t border-border">
              <button
                onClick={() => onAskAgent(displayBook.id, displayBook.title)}
                className="w-full px-4 py-2.5 bg-foreground text-background rounded-lg hover:opacity-90 transition-opacity flex items-center justify-center gap-2"
              >
                <BookOpen className="w-4 h-4" />
                <span>聊聊这本书</span>
              </button>
            </div>
          </div>

        {/* 删除确认对话框 */}
        <ConfirmDialog
          isOpen={showDeleteConfirm}
          title="从书架移除"
          message={displayBook ? `确定要将《${displayBook.title}》从书架中移除吗？` : ''}
          confirmText="确认移除"
          cancelText="取消"
          onConfirm={handleDeleteFromBookshelf}
          onCancel={() => setShowDeleteConfirm(false)}
        />
        </div>
      </div>
    </>
  )
}
